monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
        grouped:
            type: whatfailuregroup
            members: [graylog]
            channels: ["!event", "!doctrine", "!console", "!security", "!php", "!request"]
        graylog:
            type: service
            id: Monolog\Handler\GelfHandler
            level: info
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
